## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from sklearn.ensemble import RandomForestClassifier

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df_clean = application_df.drop(['EIN', 'NAME'], axis=1)
application_df_clean

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [ ]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df_clean.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
unique_count= application_df_clean['APPLICATION_TYPE'].value_counts()
unique_count

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
type_counts = application_df_clean['APPLICATION_TYPE'].value_counts()
application_types_to_replace = type_counts[type_counts < 500].index
# Replace in dataframe
for app in application_types_to_replace:
    application_df_clean['APPLICATION_TYPE'] = application_df_clean['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df_clean['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
unique_count_classification= application_df_clean['CLASSIFICATION'].value_counts()

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
unique_count_classification_above_one = unique_count_classification[unique_count_classification >1]
unique_count_classification_above_one

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = unique_count_classification[unique_count_classification <1000].index
# Replace in dataframe
for cls in classifications_to_replace:
        application_df_clean['CLASSIFICATION'] = application_df_clean['CLASSIFICATION'].replace(cls,"Other")


# Check to make sure replacement was successful
application_df_clean['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_df_encoded = pd.get_dummies(application_df_clean)
application_df_encoded_df = application_df_encoded.astype(int)
application_df_encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df_encoded_df["IS_SUCCESSFUL"]
X = application_df_encoded_df.drop(["IS_SUCCESSFUL"], axis=1)

In [ ]:
rf_model = RandomForestClassifier()
rf_model.fit(X, y)

RandomForestClassifier()

In [ ]:
importances = rf_model.feature_importances_
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.41141719236699703, 'ASK_AMT'),
 (0.13165147510347222, 'AFFILIATION_CompanySponsored'),
 (0.12372098984301211, 'AFFILIATION_Independent'),
 (0.028398277805576903, 'ORGANIZATION_Association'),
 (0.027724778574276226, 'APPLICATION_TYPE_T5'),
 (0.023150764535098966, 'APPLICATION_TYPE_T10'),
 (0.020863031037704014, 'ORGANIZATION_Trust'),
 (0.020106242178350473, 'APPLICATION_TYPE_T19'),
 (0.019000363884026004, 'CLASSIFICATION_Other'),
 (0.018010792544219674, 'CLASSIFICATION_C2100'),
 (0.015994891316860285, 'CLASSIFICATION_C2000'),
 (0.015646884130974214, 'APPLICATION_TYPE_T4'),
 (0.015384225930942415, 'APPLICATION_TYPE_T3'),
 (0.012638368420603174, 'CLASSIFICATION_C1000'),
 (0.011669610655809237, 'APPLICATION_TYPE_T6'),
 (0.01160684470887951, 'USE_CASE_ProductDev'),
 (0.010461474878164427, 'USE_CASE_Preservation'),
 (0.009332437974659446, 'CLASSIFICATION_C3000'),
 (0.008752852780271794, 'CLASSIFICATION_C1200'),
 (0.008591608904739612, 'INCOME_AMT_0'),
 (0.006205105904616943, 'INCOME_AMT_25000-99999'),
 (0.006075181471482574, 'INCOME_AMT_1M-5M'),
 (0.005970024185097557, 'INCOME_AMT_1-9999'),
 (0.005808132681474666, 'INCOME_AMT_100000-499999'),
 (0.00426332890170211, 'APPLICATION_TYPE_T8'),
 (0.003714026232648979, 'APPLICATION_TYPE_T7'),
 (0.003400354013860651, 'INCOME_AMT_10M-50M'),
 (0.0031463820737452747, 'INCOME_AMT_10000-24999'),
 (0.0029439972321782257, 'ORGANIZATION_Co-operative'),
 (0.0029122037683141115, 'USE_CASE_CommunityServ'),
 (0.0022296188926983138, 'INCOME_AMT_50M+'),
 (0.0021903520367504044, 'INCOME_AMT_5M-10M'),
 (0.002011966390947682, 'APPLICATION_TYPE_Other'),
 (0.001230057135079691, 'USE_CASE_Heathcare'),
 (0.0011854125419003172, 'AFFILIATION_Family/Parent'),
 (0.0006776451835648516, 'AFFILIATION_National'),
 (0.0005046329119110768, 'ORGANIZATION_Corporation'),
 (0.00040483218045863804, 'SPECIAL_CONSIDERATIONS_N'),
 (0.00037064760631775256, 'SPECIAL_CONSIDERATIONS_Y'),
 (0.00031205615546245997, 'AFFILIATION_Regional'),
 (0.0001688856628247757, 'STATUS'),
 (8.082185187374913e-05, 'AFFILIATION_Other'),
 (7.122741045143707e-05, 'USE_CASE_Other')]

In [54]:
application_df_encoded_df = application_df_encoded_df.drop(
    ["INCOME_AMT_1-9999", "INCOME_AMT_10000-24999", "INCOME_AMT_100000-499999",
     "INCOME_AMT_10M-50M", "INCOME_AMT_1M-5M", "INCOME_AMT_25000-99999",
     "INCOME_AMT_50M+", "SPECIAL_CONSIDERATIONS_N", "SPECIAL_CONSIDERATIONS_Y",
     "STATUS"],
    axis=1
)